# permissions for end users to edit offerings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: offering-editor-role
rules:
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - offerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - offerings/status
  verbs:
  - get
