# permissions for end users to view plans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plan-viewer-role
rules:
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - plans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - plans/status
  verbs:
  - get
