
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - credentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - credentials/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - offerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - offerings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - plans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - plans/status
  verbs:
  - get
  - patch
  - update
