
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - providers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebroker.metabroker.suse.com
  resources:
  - providers/status
  verbs:
  - get
  - patch
  - update
