FROM golang:1.15 AS staging

WORKDIR /build/helm
RUN git clone --depth 1 --branch v3.4.1 https://github.com/helm/helm.git .
RUN make

FROM opensuse/leap:15.2

COPY --from=staging /build/helm/bin/helm /usr/local/bin/helm
